---

log_level: info
mode: master

alertflow:
  url: https://alertflow.org
  runner_id: null
  api_key: null

plugins:
  - name: alertmanager
    repository: https://github.com/AlertFlow/rp-alertmanager
    version: v1.0.2

alert_endpoints:
  port: 8081
